service: cornerwise-scrapers

provider:
  name: aws
  runtime: python3.6
  timeout: 60
  profile: cornerwise
  environment:
    SOCRATA_TOKEN: ${file(./credentials.json):socrata_app_token}
    SOCRATA_SECRET: ${file(./credentials.json):socrata_app_secret}

functions:
  somervillema:
    handler: somervillema.scrape
    description: "Scrapes the OSPCD's Reports and Decisions page for recent applications submitted for review to Somerville's Planning Board and Zoning Board of Appeals."
    events:
      - http:
          path: somervillema
          method: get

  somervillema_projects:
    handler: somervillema_projects.scrape
    events:
      - http:
          path: somervillema_projects
          method: get

  somervillema_events:
    handler: somervillema_events.run
    description: "Scrapes the Somerville events page for documents related to the Planning Board and ZBA."
    timeout: 30
    events:
      - http:
          path: somervillema_events
          method: get

  cambridgema:
    handler: cambridgema.scrape
    events:
      - http:
          path: cambridgema
          method: get

  greenline:
    handler: greenline.handler
    events:
      - http:
          path: greenline
          method: get
  
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
