service: cornerwise-scrapers

provider:
  name: aws
  runtime: python3.6
  timeout: 60
  profile: cornerwise
  environment:
    SOCRATA_TOKEN: ${file(./credentials.json):socrata_app_token}
    SOCRATA_SECRET: ${file(./credentials.json):socrata_app_secret}

functions:
  somervillema:
    handler: somervillema.scrape
    events:
      - http:
          path: somervillema
          method: get

  cambridgema:
    handler: cambridgema.scrape
    events:
      - http:
          path: cambridgema
          method: get

  greenline:
    handler: greenline.handler
    events:
      - http:
          path: greenline
          method: get
  
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
